baseURL: "https://runbooks.mon.preprod.ops.daysofwonder.com"
languageCode: "en-us"
title: "kube-prometheus runbooks"

theme: book

params:
  BookRepo: "https://github.com/JBOClara/runbooks"
  BookEditPath: "edit/main"
  BookSearch: true
  BookSection: "runbooks"
  #BookMenuBundle: "/menu"

